#LOGGING
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: INFO

#SERVER
server:
  port: 8080

#SPRING
spring:
  profiles: local ,default

#DATASOURCE
datasource:
  sampleapp:
    url: jdbc:h2:mem:default/
    driverClassName: org.h2.Driver
    defaultSchema: PUBLIC
    maxPoolSize: 10
    hibernate:
      hibernate.ddl-auto: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect